#!/bin/sh

# curl -LO https://fontawesome.com/v5/cheatsheet is not a valid html
# please go to browser and inspect save body party as a fontawesome.html

raw_file="fontawesome.html"

if [ ! -f "$raw_file" ]; then
  echo "please go to https://fontawesome.com/v5/cheatsheet/ save as fontawesome.html!"
  exit
fi

grep -oE "<span[^>]+>.</span></dt> <dd[^>]+icon-name\">[^<]+<" "$raw_file" | sed -E 's/<[^>]+>(.)<.+">(.+)</\1 \2/' > fontawesome
