#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

se() { cd "$HOME/.local/bin"; fzf | xargs -r $EDITOR ;}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
  l="ls -FAhl --color=auto" \
  ll='l' \
	ls="ls -hN --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
  showip="curl -s ifconfig.me/ip"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc" \
	weath="less -S ${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport" \

# enable and diable proxy
alias \
  ep="export https_proxy=http://127.0.0.1:9000 http_proxy=http://127.0.0.1:9000 all_proxy=socks5://127.0.0.1:1089 && echo 'enable proxy: http(s)://127.0.0.1:9000'" \
  uep="unset https_proxy http_proxy all_proxy && echo disabled proxy"

# cmake build command
alias \
  cmk="cmake -Bbuild && cmake --build build -j$(nproc)" \
  cmkj="cmake -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=YES && cmake --build build -j$(nproc) && ln -sf build/compile_commands.json ."

# git
alias \
  g="git" \
  gs="git status" \
  gd="git diff" \
  ga="git add -A" \
  gam="git add -A && git commit -m" \
  gp="git push" \
  gcl="git clone"

# pacman
alias \
  pi="sudo pacman -S" \
  piy="sudo pacman -Sy" \
  pu="sudo pacman -Syyu"

# split windows with the same as current active window dir
alias sp="setsid -f $TERMINAL"

