#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 170	# Set DPI. User may want to use a larger number for larger screens.
xset r rate 300 50
# xmodmap "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap" # remaps keycode
keymap
# remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg			    # set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# use Xresources colors/settings on startup

fcitx5 --disable fcitx5-xkb -d # enable fcitx5 input

autostart="picom dunst dwmblocks pipewire mpd"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
